#pragma once

// GENERATED by tools/vehicle_specs/generate.py in the SERVE-M gamemode repository, from
// open.mp's own vehicle model table (front wheel hub height) and the game's vehicles.ide
// (wheel scale, the tyre diameter in metres). Do not edit: regenerate.
//
// The height of a vehicle's origin above the road when its tyres are on it. The NPC
// component places a driven vehicle at road + this, instead of at road + 0.5 for every
// model, which buried saloons by 0.2 m and trucks by more than a metre.

#include <cstdint>

namespace npc_navigation
{

constexpr float DefaultVehicleRestHeight = 0.5f;

inline float vehicleRestHeight(int model)
{
	switch (model)
	{
	case 400: return 0.99f;
	case 401: return 0.72f;
	case 402: return 0.70f;
	case 403: return 1.50f;
	case 404: return 0.66f;
	case 405: return 0.80f;
	case 406: return 2.39f;
	case 407: return 1.20f;
	case 408: return 1.50f;
	case 409: return 0.72f;
	case 410: return 0.60f;
	case 411: return 0.70f;
	case 412: return 0.70f;
	case 413: return 1.00f;
	case 414: return 1.00f;
	case 415: return 0.70f;
	case 416: return 1.10f;
	case 417: return 0.27f;
	case 418: return 1.03f;
	case 419: return 0.75f;
	case 420: return 0.70f;
	case 421: return 0.80f;
	case 422: return 0.90f;
	case 423: return 0.98f;
	case 424: return 0.70f;
	case 425: return 0.32f;
	case 426: return 0.70f;
	case 427: return 1.00f;
	case 428: return 1.10f;
	case 429: return 0.60f;
	case 431: return 1.00f;
	case 432: return 1.00f;
	case 433: return 1.40f;
	case 434: return 0.95f;
	case 435: return 1.50f;
	case 436: return 0.70f;
	case 437: return 1.00f;
	case 438: return 0.90f;
	case 439: return 0.80f;
	case 440: return 1.10f;
	case 441: return 0.10f;
	case 442: return 0.80f;
	case 443: return 1.50f;
	case 444: return 1.20f;
	case 445: return 0.80f;
	case 447: return 0.35f;
	case 448: return 0.50f;
	case 449: return 0.39f;
	case 450: return 1.50f;
	case 451: return 0.56f;
	case 455: return 1.40f;
	case 456: return 1.00f;
	case 457: return 0.60f;
	case 458: return 0.80f;
	case 459: return 0.99f;
	case 461: return 0.52f;
	case 462: return 0.50f;
	case 463: return 0.51f;
	case 464: return 0.41f;
	case 465: return 0.38f;
	case 466: return 0.70f;
	case 467: return 0.70f;
	case 468: return 0.60f;
	case 469: return 0.35f;
	case 470: return 0.76f;
	case 471: return 0.43f;
	case 474: return 0.70f;
	case 475: return 0.70f;
	case 476: return 0.30f;
	case 477: return 0.70f;
	case 478: return 0.90f;
	case 479: return 0.73f;
	case 480: return 0.70f;
	case 481: return 0.51f;
	case 482: return 1.00f;
	case 483: return 1.00f;
	case 485: return 0.60f;
	case 486: return 1.10f;
	case 487: return 0.35f;
	case 488: return 0.35f;
	case 489: return 1.11f;
	case 490: return 1.12f;
	case 491: return 0.74f;
	case 492: return 0.70f;
	case 494: return 0.81f;
	case 495: return 1.25f;
	case 496: return 0.67f;
	case 497: return 0.35f;
	case 498: return 0.96f;
	case 499: return 0.95f;
	case 500: return 1.02f;
	case 501: return 0.38f;
	case 502: return 0.81f;
	case 503: return 0.81f;
	case 504: return 0.70f;
	case 505: return 1.11f;
	case 506: return 0.69f;
	case 507: return 0.80f;
	case 508: return 1.30f;
	case 509: return 0.50f;
	case 510: return 0.60f;
	case 511: return 0.26f;
	case 512: return 0.35f;
	case 513: return 0.24f;
	case 514: return 1.50f;
	case 515: return 1.98f;
	case 516: return 0.79f;
	case 517: return 0.78f;
	case 518: return 0.59f;
	case 519: return 0.31f;
	case 520: return 0.35f;
	case 521: return 0.50f;
	case 522: return 0.50f;
	case 523: return 0.50f;
	case 524: return 1.80f;
	case 525: return 0.84f;
	case 526: return 0.75f;
	case 527: return 0.70f;
	case 528: return 1.03f;
	case 529: return 0.60f;
	case 530: return 0.60f;
	case 531: return 0.96f;
	case 532: return 2.00f;
	case 533: return 0.70f;
	case 534: return 0.62f;
	case 535: return 0.70f;
	case 536: return 0.70f;
	case 537: return 0.53f;
	case 538: return 0.53f;
	case 539: return 0.35f;
	case 540: return 0.82f;
	case 541: return 0.60f;
	case 542: return 0.74f;
	case 543: return 0.80f;
	case 544: return 1.20f;
	case 545: return 0.80f;
	case 546: return 0.69f;
	case 547: return 0.70f;
	case 548: return 2.80f;
	case 549: return 0.70f;
	case 550: return 0.80f;
	case 551: return 0.79f;
	case 552: return 0.60f;
	case 553: return 0.42f;
	case 554: return 0.99f;
	case 555: return 0.68f;
	case 556: return 1.20f;
	case 557: return 1.20f;
	case 558: return 0.60f;
	case 559: return 0.60f;
	case 560: return 0.60f;
	case 561: return 0.76f;
	case 562: return 0.65f;
	case 563: return 0.32f;
	case 564: return 0.10f;
	case 565: return 0.59f;
	case 566: return 0.70f;
	case 567: return 0.83f;
	case 568: return 0.78f;
	case 569: return 0.53f;
	case 570: return 0.53f;
	case 571: return 0.29f;
	case 572: return 0.59f;
	case 573: return 1.50f;
	case 574: return 0.69f;
	case 575: return 0.60f;
	case 576: return 0.60f;
	case 577: return 0.56f;
	case 578: return 1.50f;
	case 579: return 0.89f;
	case 580: return 0.69f;
	case 581: return 0.50f;
	case 582: return 1.00f;
	case 583: return 0.55f;
	case 584: return 2.01f;
	case 585: return 0.60f;
	case 586: return 0.49f;
	case 587: return 0.71f;
	case 588: return 0.90f;
	case 589: return 0.60f;
	case 590: return 0.53f;
	case 591: return 1.50f;
	case 592: return 0.47f;
	case 593: return 0.28f;
	case 594: return 0.05f;
	case 596: return 0.70f;
	case 597: return 0.70f;
	case 598: return 0.70f;
	case 599: return 1.14f;
	case 600: return 0.69f;
	case 601: return 0.75f;
	case 602: return 0.75f;
	case 603: return 0.76f;
	case 604: return 0.70f;
	case 605: return 0.80f;
	case 606: return 0.99f;
	case 607: return 1.00f;
	case 608: return 1.47f;
	case 609: return 0.96f;
	case 610: return 0.30f;
	case 611: return 0.59f;
	default: return DefaultVehicleRestHeight;
	}
}

} // namespace npc_navigation
